export const FAST_AND_SECURE_TEXT = "FAST_AND_SECURE_TEXT";
export const MONTHLY_FEES_TEXT = "MONTHLY_FEES_TEXT";
export const CONTACT_ENQUIRY = "CONTACT_ENQUIRY";

export const POST_TICKET_BUY_PENDING = "POST_TICKET_BUY_PENDING";
export const POST_TICKET_BUY_SUCCESS = "POST_TICKET_BUY_SUCCESS";
export const POST_TICKET_BUY_FAILURE = "POST_TICKET_BUY_FAILURE";

export const GET_ORDER_PENDING = "GET_ORDER_PENDING";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILURE = "GET_ORDER_FAILURE";

export const MERCHANT_INFO = "MERCHANT_INFO";

export const GET_TRANSACTIONS_PENDING = "GET_TRANSACTIONS_PENDING";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAILURE = "GET_TRANSACTIONS_FAILURE";

export const GET_MERCHANT_PRODUCTS_PENDING = "GET_MERCHANT_PRODUCTS_PENDING";
export const GET_MERCHANT_PRODUCTS_SUCCESS = "GET_MERCHANT_PRODUCTS_SUCCESS";
export const GET_MERCHANT_PRODUCTS_FAILURE = "GET_MERCHANT_PRODUCTS_FAILURE";

export const GET_MERCHANT_PRODUCT_PENDING = "GET_MERCHANT_PRODUCT_PENDING";
export const GET_MERCHANT_PRODUCT_SUCCESS = "GET_MERCHANT_PRODUCT_SUCCESS";
export const GET_MERCHANT_PRODUCT_FAILURE = "GET_MERCHANT_PRODUCT_FAILURE";

export const GET_PRODUCT_PENDING = "GET_PRODUCT_PENDING";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const GET_SERIES_TRANSACTIONS_SUCCESS =
  "GET_SERIES_TRANSACTIONS_SUCCESS";
export const GET_SERIES_TRANSACTIONS_FAILURE =
  "GET_SERIES_TRANSACTIONS_FAILURE";

export const SIGNUP_STEP_ONE = "SIGNUP_STEP_ONE";

export const ACCOUNT_UPDATE_SUCCESS = "ACCOUNT_UPDATE_SUCCESS";
export const ACCOUNT_UPDATE_FAILURE = "ACCOUNT_UPDATE_FAILURE";
export const ACCOUNT_UPDATE_PENDING = "ACCOUNT_UPDATE_PENDING";

export const SIGNUP_TOASTER_SHOWN = "SIGNUP_TOASTER_SHOWN";

export const GET_LOCATIONS_PENDING = "GET_LOCATIONS_PENDING";
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_FAILURE = "GET_LOCATIONS_FAILURE";

export const GET_PAYOUTS_PENDING = "GET_PAYOUTS_PENDING";
export const GET_PAYOUTS_SUCCESS = "GET_PAYOUTS_SUCCESS";
export const GET_PAYOUTS_FAILURE = "GET_PAYOUTS_FAILURE";

export const MAKE_MOBILE_MONEY_PAYMENT_PENDING =
  "MAKE_MOBILE_MONEY_PAYMENT_PENDING";
export const MAKE_MOBILE_MONEY_PAYMENT_SUCCESS =
  "MAKE_MOBILE_MONEY_PAYMENT_SUCCESS";
export const MAKE_MOBILE_MONEY_PAYMENT_FAILURE =
  "MAKE_MOBILE_MONEY_PAYMENT_FAILURE";

export const FINALIZE_MOBILE_MONEY_PAYMENT_PENDING =
  "FINALIZE_MOBILE_MONEY_PAYMENT_PENDING";
export const FINALIZE_MOBILE_MONEY_PAYMENT_SUCCESS =
  "FINALIZE_MOBILE_MONEY_PAYMENT_SUCCESS";
export const FINALIZE_MOBILE_MONEY_PAYMENT_FAILURE =
  "FINALIZE_MOBILE_MONEY_PAYMENT_FAILURE";
