apiVersion: v1
kind: ConfigMap
metadata:
  name: paycruiser-dev-config
  labels:
    app: paycruiser-dev
data:
  BUILD_VERSION_NUMBER: "${CIRCLE_BUILD_NUM}"


---
apiVersion: v1
kind: Service
metadata:
  name: paycruiser-dev-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    name: paycruiser-dev

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: paycruiser-dev
  labels:
    app: paycruiser-dev
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        name: paycruiser-dev
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: paycruiser-dev
          image: ${AWS_ECR_URL}/${DEVELOP_REPOSITORY_NAME}:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: paycruiser-dev-config
          resources:
            requests:
              memory: "8192Mi"
              cpu: "1024m"
            # limits:
            #   memory: "8192Mi"
            #   cpu: "1024m"
      priorityClassName: high-priority
